name: Sync from Upstream

on:
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/beck-8/subs-check.git
          git fetch upstream --tags

      - name: Merge upstream/master into current branch
        run: |
          git checkout master
          git merge upstream/master --no-edit --allow-unrelated-histories
          # 手动解决冲突并提交
          git add .github/workflows/release.yml
          git add .github/workflows/sync-upstream.yml
          git commit -m "Resolve merge conflicts"
          
      - name: Push changes and tags
        run: |
          git push origin master
          git push origin --tags
